version: '3'
services:
  redis:
    image: redis:latest
    deploy:
      replicas: 1
    container_name: redis
    ports:
      - 6379:6739
    healthcheck:
        test: ["CMD", "redis-cli","ping"]
        interval: 30s
        timeout: 10s
        retries: 3
    restart: always
